import { Ingredient } from '@/types'

export const INGREDIENTS_DATA: Ingredient[] = [
  // 채소
  { id: '1',  name: '양파',     emoji: '🧅', category: 'vegetable' },
  { id: '2',  name: '마늘',     emoji: '🧄', category: 'vegetable' },
  { id: '3',  name: '대파',     emoji: '🌿', category: 'vegetable' },
  { id: '4',  name: '당근',     emoji: '🥕', category: 'vegetable' },
  { id: '5',  name: '감자',     emoji: '🥔', category: 'vegetable' },
  { id: '6',  name: '고추',     emoji: '🌶️', category: 'vegetable' },
  { id: '7',  name: '애호박',   emoji: '🥒', category: 'vegetable' },
  { id: '8',  name: '시금치',   emoji: '🥬', category: 'vegetable' },
  { id: '9',  name: '배추',     emoji: '🥬', category: 'vegetable' },
  { id: '10', name: '버섯',     emoji: '🍄', category: 'vegetable' },
  { id: '11', name: '토마토',   emoji: '🍅', category: 'vegetable' },
  { id: '12', name: '브로콜리', emoji: '🥦', category: 'vegetable' },
  { id: '13', name: '콩나물',   emoji: '🌱', category: 'vegetable' },
  { id: '14', name: '두부',     emoji: '⬜', category: 'vegetable' },
  { id: '31', name: '깻잎',     emoji: '🌿', category: 'vegetable' },
  { id: '32', name: '부추',     emoji: '🌿', category: 'vegetable' },
  { id: '33', name: '파프리카', emoji: '🫑', category: 'vegetable' },
  { id: '34', name: '양상추',   emoji: '🥗', category: 'vegetable' },
  { id: '35', name: '오이',     emoji: '🥒', category: 'vegetable' },
  { id: '36', name: '가지',     emoji: '🍆', category: 'vegetable' },
  { id: '37', name: '단호박',   emoji: '🎃', category: 'vegetable' },
  { id: '38', name: '무',       emoji: '🫚', category: 'vegetable' },
  { id: '39', name: '팽이버섯', emoji: '🍄', category: 'vegetable' },
  { id: '40', name: '느타리버섯',emoji: '🍄', category: 'vegetable' },
  { id: '41', name: '표고버섯', emoji: '🍄', category: 'vegetable' },
  { id: '42', name: '옥수수',   emoji: '🌽', category: 'vegetable' },
  { id: '43', name: '피망',     emoji: '🫑', category: 'vegetable' },
  { id: '44', name: '쑥갓',     emoji: '🌿', category: 'vegetable' },
  { id: '45', name: '고구마',   emoji: '🍠', category: 'vegetable' },

  // 육류·달걀
  { id: '15', name: '닭가슴살', emoji: '🍗', category: 'meat' },
  { id: '16', name: '돼지고기', emoji: '🥩', category: 'meat' },
  { id: '17', name: '소고기',   emoji: '🥩', category: 'meat' },
  { id: '18', name: '달걀',     emoji: '🥚', category: 'meat' },
  { id: '46', name: '삼겹살',   emoji: '🥓', category: 'meat' },
  { id: '47', name: '닭다리살', emoji: '🍗', category: 'meat' },
  { id: '48', name: '베이컨',   emoji: '🥓', category: 'meat' },
  { id: '49', name: '소시지',   emoji: '🌭', category: 'meat' },
  { id: '50', name: '햄',       emoji: '🍖', category: 'meat' },
  { id: '51', name: '닭안심',   emoji: '🍗', category: 'meat' },

  // 해산물
  { id: '19', name: '새우',     emoji: '🍤', category: 'seafood' },
  { id: '20', name: '오징어',   emoji: '🦑', category: 'seafood' },
  { id: '21', name: '참치캔',   emoji: '🐟', category: 'seafood' },
  { id: '22', name: '멸치',     emoji: '🐟', category: 'seafood' },
  { id: '52', name: '고등어',   emoji: '🐠', category: 'seafood' },
  { id: '53', name: '꽁치',     emoji: '🐟', category: 'seafood' },
  { id: '54', name: '조개',     emoji: '🦪', category: 'seafood' },
  { id: '55', name: '김',       emoji: '🫙', category: 'seafood' },
  { id: '56', name: '미역',     emoji: '🌊', category: 'seafood' },
  { id: '57', name: '게맛살',   emoji: '🦀', category: 'seafood' },
  { id: '58', name: '굴',       emoji: '🦪', category: 'seafood' },

  // 유제품
  { id: '23', name: '우유',     emoji: '🥛', category: 'dairy' },
  { id: '24', name: '치즈',     emoji: '🧀', category: 'dairy' },
  { id: '59', name: '요거트',   emoji: '🫙', category: 'dairy' },
  { id: '60', name: '버터',     emoji: '🧈', category: 'dairy' },
  { id: '61', name: '두유',     emoji: '🥛', category: 'dairy' },

  // 곡류
  { id: '25', name: '쌀',       emoji: '🍚', category: 'grain' },
  { id: '26', name: '면',       emoji: '🍜', category: 'grain' },
  { id: '27', name: '빵',       emoji: '🍞', category: 'grain' },
  { id: '62', name: '당면',     emoji: '🍜', category: 'grain' },
  { id: '63', name: '우동면',   emoji: '🍜', category: 'grain' },
  { id: '64', name: '쌀국수',   emoji: '🍜', category: 'grain' },
  { id: '65', name: '오트밀',   emoji: '🥣', category: 'grain' },
  { id: '66', name: '식빵',     emoji: '🍞', category: 'grain' },
  { id: '67', name: '또띠아',   emoji: '🫓', category: 'grain' },

  // 과일
  { id: '28', name: '사과',     emoji: '🍎', category: 'fruit' },
  { id: '29', name: '바나나',   emoji: '🍌', category: 'fruit' },
  { id: '30', name: '레몬',     emoji: '🍋', category: 'fruit' },
  { id: '68', name: '포도',     emoji: '🍇', category: 'fruit' },
  { id: '69', name: '딸기',     emoji: '🍓', category: 'fruit' },
  { id: '70', name: '블루베리', emoji: '🫐', category: 'fruit' },
  { id: '71', name: '복숭아',   emoji: '🍑', category: 'fruit' },
  { id: '72', name: '키위',     emoji: '🥝', category: 'fruit' },
  { id: '73', name: '수박',     emoji: '🍉', category: 'fruit' },
  { id: '74', name: '배',       emoji: '🍐', category: 'fruit' },
]
